# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: |
          npm install 
          npm run build
          cd /dist
          zip -q -r tetris.zip ./
      - name: 读取webApp json 的信息
        uses: antifree/json-to-variables@v1.0.1
        with:
          filename: 'webApp.json'
          prefix: webApp
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "tetris.zip"
          tag: v${{ env.webApp_version }}
          name:  v${{ env.webApp_version }}
          token: ${{ secrets.GITHUB_TOKEN }}
